Update Janino.java
There are two fields in the table: XXXUID_(varchar2), UID_(bigint), for varchar2 type data encrypted, when decrypting the use of contains() method will not need to be decrypted uid_ field will also be included, resulting in decrypted fields more than encrypted fields, there is an exception: org.pentaho. di.core.exception.KettleValueException. 
	java.lang.IllegalArgumentException: parameter type mismatch